Once applied, the plugin adds a https://github.com/britter/maven-plugin-development/blob/0.1.0/src/main/kotlin/de/benediktritter/maven/plugin/development/MavenPluginDevelopmentExtension.kt[`MavenPluginDevelopmentExtension`] with name `mavenPlugin` to the project.
All meta data for the plugin, e.g. `groupId`, `artifactId`, `description` is extracted from the corresponding project properties.

[source.multi-language-sample,groovy,subs="attributes+,verbatim"]
----
plugins {
    id 'de.benediktritter.maven-plugin-development' version '{gradle-project-version}'
}
----
[source.multi-language-sample,kotlin,subs="attributes+"]
----
plugins {
    id("de.benediktritter.maven-plugin-development") version "{gradle-project-version}"
}
----

== HelpMojo generation

It's possible to generate a help mojo that help users to discover the functionality of your Maven plugin.
By default generation of a help mojo is disabled.
To enable it specify the package the HelpMojo should be generated in:

[source.multi-language-sample,groovy]
----
include::{snippets-path}/help-mojo/groovy/build.gradle[tags=help-mojo]
----
[source.multi-language-sample,kotlin]
----
include::{snippets-path}/help-mojo/kotlin/build.gradle.kts[tags=help-mojo]
----

== Extracting mojos from other subprojects

The plugin will create a configuration called `mojo` and add it to the project.
All project dependencies added to this configuration will be searched for mojo implementations.

[source.multi-language-sample,groovy]
----
include::{snippets-path}/mojo-subproject/groovy/plugin/build.gradle[tags=mojo-subproject]
----
[source.multi-language-sample,kotlin]
----
include::{snippets-path}/mojo-subproject/kotlin/plugin/build.gradle.kts[tags=mojo-subproject]
----

== Controlling plugin dependencies

By default all dependencies from the runtime classpath will in added to the dependencies blog of the generated plugin descriptor.
The can be changed by configuring the `dependencies` property on the `mavenPlugin` extension.
In the following examples only `org.apache.commons:commons-lang3:3.9` will be added as a dependency to the plugin descriptor:

[source.multi-language-sample,groovy]
----
include::{snippets-path}/dependencies/groovy/build.gradle[tags=dependencies]
----
[source.multi-language-sample,kotlin]
----
include::{snippets-path}/dependencies/kotlin/build.gradle.kts[tags=dependencies]
----

== Defining mojos in the build script

If you can't or don't want to use auto detection of mojos there is also a DSL for defining mojos inside the build script:

[source.multi-language-sample,groovy]
----
include::{snippets-path}/buildscript-dsl/groovy/build.gradle[tags=buildscript-dsl]
----
[source.multi-language-sample,kotlin]
----
include::{snippets-path}/buildscript-dsl/kotlin/build.gradle.kts[tags=buildscript-dsl]
----
