= Release History

== 0.3.1

Release date: 2020-09-27

=== Changes

* Build cache support ({gh-issue}7[#7])
* Plugin jar contains LICENSE file ({gh-issue}26[#26])
* Additional project metadata added to published plugin POMs ({gh-issue}47[#47])
* More idiomatic task dependency modelling ({gh-issue}35[#35])

== 0.3.0

Release date: 2020-08-02

*Note:* This release includes a change in behavior of the HelpMojo generation.
Before 0.3.0 generation of a HelpMojo could be turned on by setting `generateHelpMojo` to `true`.
Starting with 0.3.0 `generateHelpMojo` is deprecated and replaced by `helpMojoPackage`.
Users now need to define the package of the HelpMojo.
This fixes problems with up-to-date checking (see {gh-issue}16[#16]).

=== Bug fixes

* Task descriptions for help and descriptor task are swapped ({gh-issue}34[#34])
* Help mojo task is never up to date because descriptor tasks modifies outputs ({gh-issue}16[#16])

=== Deprecations

* The `generateHelpMojo` setting has been deprecated in favor of `helpMojoPackage`

=== Breaking changes

* Class `de.benediktritter.maven.plugin.development.task.HelpGeneratorAccessor` has been removed

== 0.2.1

Release date: 2020-05-02

=== New Features

* Tasks provide proper descriptions ({gh-issue}22[#22])

=== Bug Fixes

* Build fails when `java` plugin is not applied explicitly ({gh-issue}19[#19])
* Typing of `parameters` API is incorrect ({gh-issue}23[#23])

== 0.2.0

Release date: 2020-04-16

=== New Features

* Add DSL for declaring mojos in the build script ({gh-issue}4[#4])
* Provide way to configure plugin dependencies ({gh-issue}12[#12])
* Define dedicated configuration for projects providing mojos ({gh-issue}11[#11])
* Add support for mojos from other projects ({gh-issue}3[#3])

=== Bug Fixes

* Force version upgrade of qdox ({gh-issue}9[#9])

=== Breaking changes

* Package `de.benediktritter.maven.plugin.development.model` has been removed.

== 0.1.0

Release date: 2020-04-05

Initial release
