= Maven Plugin Development Gradle Plugin

image:https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fbritter%2Fmaven-plugin-development%2Fbadge%3Fref%3Dmaster&style=flat["Build Status", link="https://actions-badge.atrox.dev/britter/maven-plugin-development/goto?ref=master"]
image:https://img.shields.io/maven-metadata/v?label=Plugin%20Portal&metadataUrl=https%3A%2F%2Fplugins.gradle.org%2Fm2%2Fde%2Fbenediktritter%2Fmaven-plugin-development%2Fde.benediktritter.maven-plugin-development.gradle.plugin%2Fmaven-metadata.xml["Gradle Plugin Portal", link="https://plugins.gradle.org/plugin/de.benediktritter.maven-plugin-development"]

This plugin aims to fill the tiny gap for people who need to create an https://maven.apacke.org[Apache Maven] plugin from a Gradle build.
To do this the plugin wraps around the https://maven.apache.org/plugin-tools/[Maven Plugin Tools API] and feeds it with the right inputs from the Gradle build.

== Features

- Automatic generation of a maven plugin descriptor containing all mojos in the selected source set (by default the plugin looks for mojo implementations in the main source set)
- Support for annotation and JavaDoc tag based mojo implementations
- Optional generation of a help mojo implementation

== Usage

Once applied, the plugin adds a https://github.com/britter/maven-plugin-development/blob/0.1.0/src/main/kotlin/de/benediktritter/maven/plugin/development/MavenPluginDevelopmentExtension.kt[`MavenPluginDevelopmentExtension`] with name `mavenPlugin` to the project.
All meta data for the plugin, e.g. `groupId`, `artifactId`, `description` is extracted from the corresponding project properties.

[source.multi-language-sample,groovy,subs="attributes+,verbatim"]
----
plugins {
    id 'de.benediktritter.maven-plugin-development' version '{gradle-project-version}'
}
----
[source.multi-language-sample,kotlin,subs="attributes+"]
----
plugins {
    id("de.benediktritter.maven-plugin-development") version "{gradle-project-version}"
}
----

== HelpMojo generation

It's possible to generate a help mojo that help users to discover the functionality of your Maven plugin.
By default generation of a help mojo is disabled.
To enable it add the following configuration

[source.multi-language-sample,groovy]
----
include::src/docs/snippets/help-mojo/groovy/build.gradle[tags=help-mojo]
----
[source.multi-language-sample,kotlin]
----
include::src/docs/snippets/help-mojo/kotlin/build.gradle.kts[tags=help-mojo]
----

== Extracting mojos from other subprojects

The plugin will create a configuration called `mojo` and add it to the project.
All project dependencies added to this configuration will be searched for mojo implementations.

[source.multi-language-sample,groovy]
----
include::src/docs/snippets/mojo-subproject/groovy/plugin/build.gradle[tags=mojo-subproject]
----
[source.multi-language-sample,kotlin]
----
include::src/docs/snippets/mojo-subproject/kotlin/plugin/build.gradle.kts[tags=mojo-subproject]
----

== Controlling plugin dependencies

By default all dependencies from the runtime classpath will in added to the dependencies blog of the generated plugin descriptor.
The can be changed by configuring the `dependencies` property on the `mavenPlugin` extension.
In the following examples only `org.apache.commons:commons-lang3:3.9` will be added as a dependency to the plugin descriptor:

[source.multi-language-sample,groovy]
----
include::src/docs/snippets/dependencies/groovy/build.gradle[tags=dependencies]
----
[source.multi-language-sample,kotlin]
----
include::src/docs/snippets/dependencies/kotlin/build.gradle.kts[tags=dependencies]
----

== Defining mojos in the build script

If you can't or don't want to use auto detection of mojos there is also a DSL for defining mojos inside the build script:

[source.multi-language-sample,groovy]
----
include::src/docs/snippets/buildscript-dsl/groovy/build.gradle[tags=buildscript-dsl]
----
[source.multi-language-sample,kotlin]
----
include::src/docs/snippets/buildscript-dsl/kotlin/build.gradle.kts[tags=buildscript-dsl]
----
