Once applied, the plugin adds a https://github.com/britter/maven-plugin-development/blob/0.1.0/src/main/kotlin/de/benediktritter/maven/plugin/development/MavenPluginDevelopmentExtension.kt[`MavenPluginDevelopmentExtension`] with name `mavenPlugin` to the project.
All meta data for the plugin, e.g. `groupId`, `artifactId`, `description` is extracted from the corresponding project properties.

[source.multi-language-sample,groovy,subs="attributes+,verbatim"]
----
plugins {
    id 'de.benediktritter.maven-plugin-development' version '{gradle-project-version}'
}
----
[source.multi-language-sample,kotlin,subs="attributes+"]
----
plugins {
    id("de.benediktritter.maven-plugin-development") version "{gradle-project-version}"
}
----

== HelpMojo generation

It's possible to generate a help mojo that help users to discover the functionality of your Maven plugin.
By default generation of a help mojo is disabled.
To enable it specify the package the HelpMojo should be generated in:

[source.multi-language-sample,groovy]
----
include::{snippets-path}/help-mojo/groovy/build.gradle[tags=help-mojo]
----
[source.multi-language-sample,kotlin]
----
include::{snippets-path}/help-mojo/kotlin/build.gradle.kts[tags=help-mojo]
----

== Controlling plugin dependencies

By default, all dependencies from the runtime classpath will be added to the dependencies block of the generated plugin descriptor.
This can be changed by configuring the `dependencies` property on the `mavenPlugin` extension.
In the following examples only `org.apache.commons:commons-lang3:3.9` will be added as a dependency to the plugin descriptor:

[source.multi-language-sample,groovy]
----
include::{snippets-path}/dependencies/groovy/build.gradle[tags=dependencies]
----
[source.multi-language-sample,kotlin]
----
include::{snippets-path}/dependencies/kotlin/build.gradle.kts[tags=dependencies]
----
