name: Cross version tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  provide-versions:
    name: "Provide versions for testing"
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
      - name: Write version data
        id: write-versions
        run: "./gradlew :plugin:writeVersions"
      - name: Export versions output
        id: export-versions
        run: echo "::set-output name=versions::$(cat subprojects/plugin/build/ci/gradle-versions.json)"
    outputs:
      versions: ${{ steps.export-versions.outputs.versions }}
  cross-version-tests:
    name: "Gradle cross version tests"
    needs: provide-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.provide-versions.outputs.versions) }}
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
      - name: "Test Gradle ${{ matrix.version }}"
        run: "./gradlew :plugin:compatTest${{ matrix.version }}"
